const obj = {
    market: [{
        left: 16,
        right: 365,
        top: 26,
        bottom: 220,
        width: 80,
        height: 19,
        type: 'rect',
    }, {
        left: 274,
        right: 365,
        top: 28,
        bottom: 220,
        width: 100,
        height: 12,
        type: 'rect',
    },
    {
        left: 354,
        right: 365,
        top: 50,
        bottom: 220,
        width: 20,
        height: 19,
        type: 'rect',
    },
    {
        left: 16,
        right: 365,
        top: 90,
        bottom: 220,
        width: 16,
        height: 16,
        type: 'rect',
    },
    {
        left: 108,
        right: 365,
        top: 90,
        bottom: 220,
        width: 80,
        height: 12,
        type: 'rect',
    },
    {
        left: 212,
        right: 365,
        top: 90,
        bottom: 220,
        width: 24,
        height: 12,
        type: 'rect',
    },
    {
        left: 350,
        right: 365,
        top: 90,
        bottom: 220,
        width: 24,
        height: 12,
        type: 'rect',
    },
    {
        left: 16,
        right: 365,
        top: 116,
        bottom: 220,
        width: 36,
        height: 16,
        type: 'rect',
    },
    {
        left: 360,
        right: 365,
        top: 122,
        bottom: 220,
        width: 14,
        height: 12,
        type: 'rect',
    },
    {
        left: 16,
        right: 365,
        top: 140,
        bottom: 220,
        width: 50,
        height: 16,
        type: 'rect',
    }, {
        left: 244,
        right: 365,
        top: 146,
        bottom: 220,
        width: 130,
        height: 12,
        type: 'rect',
    },
    ],
}
export default obj
