const obj = {
    market: [{
        left: 10,
        top: 15,
        bottom: 220,
        width: 45,
        height: 45,
        type: 'round',
    }, {
        left: 60,
        right: 365,
        top: 12,
        bottom: 220,
        width: 90,
        height: 19,
        type: 'rect',
    }, {
        left: 60,
        right: 365,
        top: 40,
        bottom: 220,
        width: 55,
        height: 19,
        type: 'rect',
    }, {
        left: 200,
        right: 365,
        top: 25,
        bottom: 220,
        width: 90,
        height: 19,
        type: 'rect',
    }, {
        left: 300,
        right: 365,
        top: 15,
        bottom: 220,
        width: 80,
        height: 40,
        type: 'rect',
    }],
    top: [
        {
            left: 14,
            right: 365,
            top: 16,
            bottom: 220,
            width: 70,
            height: 20,
            type: 'rect',
        }, {
            left: 14,
            right: 365,
            top: 42,
            bottom: 220,
            width: 134,
            height: 24,
            type: 'rect',
        }, {
            left: 14,
            right: 365,
            top: 72,
            bottom: 220,
            width: 134,
            height: 65,
            type: 'rect',
        }, {
            left: 14,
            right: 365,
            top: 142,
            bottom: 220,
            width: 70,
            height: 28,
            type: 'rect',
        }, {
            left: 118,
            right: 365,
            top: 142,
            bottom: 220,
            width: 30,
            height: 28,
            type: 'rect',
        },
    ],
    swipers:[
        {
            left: 14,
            right: 365,
            top: 16,
            bottom: 220,
            width: 229,
            height: 30,
            type: 'rect',
        },
        {
            left: 14,
            right: 365,
            top: 94,
            bottom: 220,
            width: 362,
            height: 30,
            type: 'rect',
        },
        {
            left: 269,
            right: 365,
            top: 17,
            bottom: 220,
            width: 107,
            height: 66,
            type: 'rect',
        }
    ]
}
export default obj
