/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "pages/history" |
       "pages/home" |
       "pages/mine" |
       "pages/position" |
       "pages/quotes" |
       "pages-sub/acticity/detail" |
       "pages-sub/user/avatar-cropper" |
       "pages-sub/user/login";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "pages/home" | "pages/quotes" | "pages/position" | "pages/history" | "pages/mine"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
